# For production
SERVERADDRESS = None
SERVERIP = None

CHUNKSIZE = 16
MAPDIMENSIONS = (CHUNKSIZE * 5, CHUNKSIZE * 5) # Min 61*39
CLIENTDIMENSIONS = (61, 39)
DEFAULTNAME = "An unnamed bit"
MAXNAMELENGTH = 20

LOGGING = True
TICKRATE = 15

MINUTE = 60 # Make 30 to make game run 2x faster
SHOOTDELAY = 4/(TICKRATE + 3) # Seconds
MINEDELAY = 2 # Seconds

GEYSERCHANCE = 15 # 1/15 chance
GEYSERLIFESPAN = 20 # min
GEYSERGAIN = 2 # Per minute
GEYSERMAXGAIN = MINUTE * 8

DOORCOST = 400
DOORHEALTH = 6
FORTIFYCOST = 100
FORTIFYHEALTH = 5

BOTAMOUNT = (MAPDIMENSIONS[0] * MAPDIMENSIONS[1]) / (60**2) # 1 bot per 60^2 area
BOTRANDOMTURNCHANCE = 20
BOTSNIFFRANGE = 10
BORERRORRATE = 10 # 1/10

PLAYER_CHAR = "@"
WALL_CHAR = "#"
BOULDER_CHAR = "O"
GRASS_CHAR = "."
GRASS_ALT_CHAR = "_"
LADDER_CHAR = "H"
BUSH_CHAR = "B"
GEYSER_CHAR = "M"
DOOR_CHAR = "D"
FORTIFIED_CHAR = "█"
EMPTY_CHAR = " "

# Can't shoot nor move through
PLAYER_CAN_MOVE_THROUGH = [EMPTY_CHAR, GRASS_CHAR, GRASS_ALT_CHAR, LADDER_CHAR, BUSH_CHAR, DOOR_CHAR]